/*
  1. 2022년 1월 저자 별, 카테고리 별 매출액(판매량*판매가)
  2. AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES
  3. 정렬 : 저자ID ASC, 카테고리 DESC
*/
-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * SALES.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
INNER JOIN
    AUTHOR
    ON B.AUTHOR_ID = AUTHOR.AUTHOR_ID
INNER JOIN
    BOOK_SALES AS SALES
    ON B.BOOK_ID = SALES.BOOK_ID
WHERE
    SALES.SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
GROUP BY
    B.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    B.AUTHOR_ID ASC,
    B.CATEGORY DESC;
