-- 코드를 작성해주세요
# SELECT  II.ITEM_ID
#         ,II.ITEM_NAME
#   FROM  ITEM_INFO AS II
#   LEFT
#   JOIN  ITEM_TREE AS IT
#     ON  II.ITEM_ID = IT.ITEM_ID
#  WHERE  IT.PARENT_ITEM_ID IS NULL
#  ORDER
#     BY  II.ITEM_ID ASC;

SELECT
    INFO.ITEM_ID,
    INFO.ITEM_NAME
FROM
    ITEM_INFO AS INFO
INNER JOIN
    ITEM_TREE AS TREE
    ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE
    TREE.PARENT_ITEM_ID IS NULL
ORDER BY
    1 ASC;