-- 코드를 입력하세요
# SELECT  ANIMAL_ID
#         ,NAME
#   FROM  ANIMAL_INS
#  WHERE  NAME LIKE '%EL%'
#    AND  ANIMAL_TYPE = 'Dog'
#  ORDER
#     BY  NAME ASC;

SELECT
    ANIMAL_ID,
    NAME
FROM
    ANIMAL_INS
WHERE
    ANIMAL_TYPE LIKE 'Dog'
    AND NAME LIKE '%el%'
ORDER BY
    2 ASC;