-- 코드를 입력하세요
# SELECT  P.PRODUCT_CODE
#         ,SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
#   FROM  PRODUCT AS P
#   LEFT  
#   JOIN  OFFLINE_SALE AS O
#     ON  P.PRODUCT_ID = O.PRODUCT_ID
#  WHERE  O.SALES_AMOUNT IS NOT NULL
#  GROUP
#     BY  P.PRODUCT_CODE
#  ORDER
#     BY  SALES DESC
#         ,P.PRODUCT_CODE ASC;

SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE AS OS
INNER JOIN
    PRODUCT AS P
    ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    2 DESC,
    1 ASC;