-- 코드를 입력하세요
# SELECT  COUNT(*)
#   FROM  USER_INFO
#  WHERE  YEAR(JOINED) = 2021
#    AND  AGE BETWEEN 20 AND 29;

# SELECT
#     COUNT(*) AS USERS
# FROM
#     USER_INFO
# WHERE
#     AGE IS NOT NULL
#     AND AGE BETWEEN 20 AND 29
#     AND YEAR(JOINED) LIKE 2021;

SELECT
    COUNT(DISTINCT USER_ID) AS USERS
FROM
    USER_INFO
WHERE
    YEAR(JOINED) = 2021
    AND AGE BETWEEN 20 AND 29;