-- 코드를 입력하세요
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1-DP.DISCOUNT_RATE/100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON C.CAR_TYPE = DP.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('SUV', '세단')
    AND DP.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
    )
GROUP BY
    C.CAR_ID,
    C.CAR_TYPE
HAVING
    FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;
