-- 코드를 입력하세요
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM
    (
        SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE, FAVORITES
        ORDER BY FOOD_TYPE DESC, FAVORITES DESC
    ) AS REST
GROUP BY
    FOOD_TYPE
HAVING
    FAVORITES = MAX(FAVORITES);