-- 코드를 입력하세요
# SELECT
#     U_BOARD.WRITER_ID,
#     U_USER.NICKNAME,
#     CONCAT(U_USER.CITY, ' ', U_USER.STREET_ADDRESS1, ' ', U_USER.STREET_ADDRESS2) AS '전체주소',
#     CONCAT(LEFT(U_USER.TLNO,3), '-', SUBSTRING(U_USER.TLNO, 4, 4), '-', RIGHT(U_USER.TLNO, 4)) AS '전화번호'
# FROM
#     USED_GOODS_BOARD AS U_BOARD
# INNER JOIN
#     USED_GOODS_USER AS U_USER
# ON
#     U_BOARD.WRITER_ID = U_USER.USER_ID
# GROUP BY
#     U_BOARD.WRITER_ID
# HAVING
#     COUNT(WRITER_ID) >= 3
# ORDER BY
#     U_BOARD.WRITER_ID DESC;


/*
 중고 거래 게시물을 3건 이상 등록한 사용자
*/

WITH FIND_THREE_WRITER AS (
    SELECT
        WRITER_ID
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT(*) >= 3
)
SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO,4,4),'-',RIGHT(TLNO,4)) AS '전화번호'
FROM
    USED_GOODS_USER
WHERE
    USER_ID IN (SELECT WRITER_ID FROM FIND_THREE_WRITER)
ORDER BY
    1 DESC;