-- 코드를 입력하세요
# SELECT  *
#   FROM  FOOD_PRODUCT
#  WHERE  PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

WITH FIND_MAX_PRICE AS (
    SELECT
        MAX(PRICE) AS MAX_PRICE
    FROM
        FOOD_PRODUCT
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM
    FOOD_PRODUCT
WHERE
    PRICE IN (SELECT MAX_PRICE FROM FIND_MAX_PRICE);