/*
1. 평균 대여 기간 7일 이상인 자동차
2. 자동차 ID, 평균 대여 기간(첫째자리)
3. 정렬 : 평균 대여기간 DESC, 자동차 ID ASC 
*/

SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC,
    CAR_ID DESC;