-- 코드를 작성해주세요
# SELECT  COUNT(*) AS FISH_COUNT
#   FROM  FISH_INFO
#  WHERE  YEAR(TIME) = 2021;

# SELECT
#     COUNT(ID) AS FISH_COUNT
# FROM
#     FISH_INFO
# WHERE
#     TIME LIKE '%2021%'

SELECT
    COUNT(ID) AS FISH_COUNT
FROM
    (SELECT ID FROM FISH_INFO WHERE YEAR(TIME) = 2021) T1;
    