-- 코드를 입력하세요
SELECT
    AI.NAME,
    AI.DATETIME
FROM
    ANIMAL_INS AS AI
WHERE
    AI.ANIMAL_ID NOT IN (
        SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
    )
ORDER BY
    AI.DATETIME ASC
LIMIT 3;