-- 코드를 입력하세요
# SELECT
#     FP.PRODUCT_ID,
#     FP.PRODUCT_NAME,
#     SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
# FROM
#     FOOD_ORDER AS FO
# LEFT JOIN
#     FOOD_PRODUCT AS FP
# ON
#     FO.PRODUCT_ID = FP.PRODUCT_ID
# WHERE
#     FO.PRODUCE_DATE LIKE ('%2022-05%')
# GROUP BY
#     FP.PRODUCT_ID,
#     FP.PRODUCT_NAME
# ORDER BY 
#     TOTAL_SALES DESC,
#     FP.PRODUCT_ID ASC;

WITH FIND_MAY_FOOD AS (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS AMT
    FROM
        FOOD_ORDER
    WHERE
        MONTH(PRODUCE_DATE) = 5
    GROUP BY
        PRODUCT_ID
)
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    (FP.PRICE * FMF.AMT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS FP
INNER JOIN
    FIND_MAY_FOOD AS FMF
    ON FP.PRODUCT_ID = FMF.PRODUCT_ID
GROUP BY
    FP.PRODUCT_ID
ORDER BY
    3 DESC,
    1 ASC;