-- 코드를 입력하세요
# SELECT
#     UUSER.USER_ID,
#     UUSER.NICKNAME,
#     SUM(BOARD.PRICE) AS TOTAL_SALES
# FROM
#     USED_GOODS_BOARD AS BOARD
# INNER JOIN
#     USED_GOODS_USER AS UUSER
# ON
#     BOARD.WRITER_ID = UUSER.USER_ID
# WHERE
#     BOARD.STATUS = 'DONE'
# GROUP BY
#     UUSER.USER_ID,
#     UUSER.NICKNAME
# HAVING
#     TOTAL_SALES >= 700000
# ORDER BY
#     TOTAL_SALES ASC;

WITH CHECK_HIGH_USER AS (
    SELECT
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = 'DONE'
    GROUP BY
        WRITER_ID
    HAVING
        SUM(PRICE) >= 700000
)
SELECT
    USER_ID,
    NICKNAME,
    TOTAL_SALES
FROM
    USED_GOODS_USER AS UGU
INNER JOIN
    CHECK_HIGH_USER AS CHU
    ON UGU.USER_ID = CHU.WRITER_ID
ORDER BY
    3 ASC;
