/*
 1. 리뷰를 가장 많이 작성한 회원의 리뷰 조회
 2. 회원 이름, 리뷰 텍스트, 리뷰 작성일
 3. 정렬 : 리뷰 작성일, 리뷰 텍스트 오름차순
*/
-- 코드를 입력하세요
# WITH REVIEW_COUNTS AS (
#     SELECT 
#         MEMBER_ID,
#         COUNT(*) AS REVIEW_COUNT
#     FROM 
#         REST_REVIEW
#     GROUP BY
#         MEMBER_ID
# ),
# MAX_REVIEWER AS (
#     SELECT
#         MEMBER_ID
#     FROM
#         REVIEW_COUNTS
#     WHERE
#         REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNTS)
# )

# SELECT
#     MEM.MEMBER_NAME,
#     REVIEW.REVIEW_TEXT,
#     DATE_FORMAT(REVIEW.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM
#     REST_REVIEW AS REVIEW
# INNER JOIN
#     MEMBER_PROFILE AS MEM
#     ON REVIEW.MEMBER_ID = MEM.MEMBER_ID
# WHERE
#     REVIEW.MEMBER_ID IN (
#         SELECT MEMBER_ID
#         FROM MAX_REVIEWER
#     )
# ORDER BY
#     REVIEW.REVIEW_DATE ASC,
#     REVIEW.REVIEW_TEXT ASC;



/*
 - 리뷰를 가장 많이 작성한 회원의 리뷰조회
 - 리뷰 작성일, 리뷰 텍스트 오름차순 정렬
*/

WITH FIND_MOST_REVIEWER AS(
    SELECT
        MEMBER_ID,
        COUNT(MEMBER_ID) AS MEMBER_ID_CNT
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        2 DESC
    LIMIT 1
)

SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW AS RR
INNER JOIN
    FIND_MOST_REVIEWER AS FMR
    ON RR.MEMBER_ID = FMR.MEMBER_ID
INNER JOIN
    MEMBER_PROFILE AS MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY
    3 ASC,
    2 ASC;

