-- 코드를 입력하세요
# SELECT
#     MONTH(START_DATE) AS MONTH,
#     CAR_ID,
#     COUNT(*) AS RECORDS
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
#     CAR_ID IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
#         GROUP BY CAR_ID
#         HAVING COUNT(CAR_ID) >= 5
#     )
#     AND (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
# GROUP BY
#     MONTH(START_DATE),
#     CAR_ID
# ORDER BY
#     MONTH ASC,
#     CAR_ID DESC;

WITH CHECK_RENTAL_CAR_LIST AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
)
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (SELECT CAR_ID FROM CHECK_RENTAL_CAR_LIST)
GROUP BY
    CAR_ID,
    MONTH
ORDER BY
    1 ASC,
    2 DESC;