-- 코드를 작성해주세요
-- 1. 연도별 MAX SIZE_OF_COLONY
-- 2. 연도별 1. - SIZE_OF_COLONY
WITH MAX_SIZE_OF_COLONY AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR_DIFF,
        MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    MSOC.YEAR_MAX - ED.SIZE_OF_COLONY AS YEAR_DEV,
    ED.ID
FROM
    ECOLI_DATA AS ED
INNER JOIN
    MAX_SIZE_OF_COLONY AS MSOC
    ON YEAR(ED.DIFFERENTIATION_DATE) = MSOC.YEAR_DIFF
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC;
