-- 코드를 입력하세요
# SELECT
#     RENTAL.CAR_ID
# FROM
#     CAR_RENTAL_COMPANY_CAR AS RENTAL
# WHERE
#     RENTAL.CAR_ID IN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE MONTH(START_DATE) = 10
#     )
#     AND RENTAL.CAR_TYPE = '세단'
# ORDER BY
#     RENTAL.CAR_ID DESC;
WITH CHECK_CAR AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_CAR
    WHERE
        CAR_TYPE LIKE ('세단')
)
SELECT
    DISTINCT(CAR_ID)
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN (SELECT CAR_ID FROM CHECK_CAR)
    AND MONTH(START_DATE) LIKE 10
ORDER BY
    1 DESC;