-- 코드를 작성해주세요
# WITH MAX_LENGTH_FISH AS (
#     SELECT
#         FI.FISH_TYPE,
#         MAX(FI.LENGTH) AS MAX_LENGTH
#     FROM
#         FISH_INFO AS FI
#     GROUP BY
#         FI.FISH_TYPE
# )

# SELECT 
#     FI.ID,
#     FNI.FISH_NAME,
#     FI.LENGTH
# FROM
#     FISH_INFO AS FI
# JOIN
#     MAX_LENGTH_FISH AS MLF
#     ON FI.FISH_TYPE = MLF.FISH_TYPE AND FI.LENGTH = MLF.MAX_LENGTH
# JOIN
#     FISH_NAME_INFO AS FNI
#     ON FI.FISH_TYPE = FNI.FISH_TYPE
# ORDER BY
#     FI.ID ASC;
    

/*
 - 물고기 종류별 가장 큰 물고기의 ID, 이름, 길이 출력
 - 물고기 ID ASC 정렬
*/

WITH FIND_MAX_FISH_LIST AS (
    SELECT 
        ROW_NUMBER() OVER(PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS RN_NUM,
        FI.ID,
        FI.LENGTH,
        FNI.FISH_NAME
    FROM
        FISH_INFO AS FI
    INNER JOIN
        FISH_NAME_INFO AS FNI
        ON FI.FISH_TYPE = FNI.FISH_TYPE
)
SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM
    FIND_MAX_FISH_LIST
WHERE
    RN_NUM = 1
ORDER BY
    ID ASC;