-- 코드를 작성해주세요
SELECT  SUM(GRADE.SCORE) AS SCORE
        ,GRADE.EMP_NO
        ,EMPLOYEES.EMP_NAME
        ,EMPLOYEES.POSITION
        ,EMPLOYEES.EMAIL
  FROM  HR_GRADE AS GRADE
  LEFT  
  JOIN  HR_EMPLOYEES AS EMPLOYEES
    ON  GRADE.EMP_NO = EMPLOYEES.EMP_NO
  LEFT
  JOIN  HR_DEPARTMENT AS DEPARTMENT
    ON  EMPLOYEES.DEPT_ID = DEPARTMENT.DEPT_ID
 GROUP
    BY  GRADE.EMP_NO
        ,EMPLOYEES.EMP_NAME
        ,EMPLOYEES.POSITION
        ,EMPLOYEES.EMAIL
HAVING  SUM(GRADE.SCORE) =
            (SELECT  MAX(SUM_SCORE)
               FROM
                (SELECT  SUM(SCORE) AS SUM_SCORE
                   FROM  HR_GRADE
                  GROUP
                     BY  EMP_NO) AS MAX_SCORE
            );