-- 코드를 입력하세요
# SELECT  I.INGREDIENT_TYPE
#         ,SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
#   FROM  FIRST_HALF AS F
#   LEFT
#   JOIN  ICECREAM_INFO AS I
#     ON  F.FLAVOR = I.FLAVOR
#  GROUP
#     BY  I.INGREDIENT_TYPE
#  ORDER
#     BY  TOTAL_ORDER ASC;

SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS FH
INNER JOIN
    ICECREAM_INFO AS II
    ON FH.FLAVOR = II.FLAVOR
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    2 ASC;