-- 코드를 입력하세요
# 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT  UGB.TITLE
        ,UGB.BOARD_ID
        ,UGR.REPLY_ID
        ,UGR.WRITER_ID
        ,UGR.CONTENTS
        ,DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATE_DATE
  FROM  USED_GOODS_BOARD AS UGB
  LEFT
  JOIN  USED_GOODS_REPLY AS UGR
    ON  UGB.BOARD_ID = UGR.BOARD_ID
 WHERE  UGB.CREATED_DATE LIKE ('%2022-10%')
   AND  UGR.REPLY_ID IS NOT NULL
 ORDER
    BY  UGR.CREATED_DATE ASC
        ,UGB.TITLE ASC;