-- 코드를 입력하세요
# SELECT
#     B.CATEGORY,
#     SUM(SALES) AS TOTAL_SALES
# FROM
#     BOOK AS B
# LEFT JOIN
#     BOOK_SALES AS BS
# ON
#     B.BOOK_ID = BS.BOOK_ID
# WHERE
#     BS.SALES_DATE LIKE ('%2022-01%')
# GROUP BY
#     B.CATEGORY
# ORDER BY
#     B.CATEGORY;


WITH CHECK_BOOK_SALES AS (
    SELECT
        BOOK_ID,
        SUM(SALES) AS CNT_SALES
    FROM
        BOOK_SALES
    WHERE
        SALES_DATE LIKE ('2022-01%')
    GROUP BY
        BOOK_ID
)
SELECT
    CATEGORY,
    SUM(CNT_SALES) AS TOTAL_SALES
FROM
    BOOK AS B
INNER JOIN
    CHECK_BOOK_SALES AS CBS
    ON B.BOOK_ID = CBS.BOOK_ID
GROUP BY
    CATEGORY
ORDER BY
    1 ASC;